In [1]:
import altair as alt
import pandas as pd
import numpy as np


data = pd.read_excel("LPD2022_public.xlsx")
data.head()

,ID,Binomial,Replicate,Excluded_LPR_2022,Citation,Class,Order,Family,Genus,Species,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,1,Balearica_regulorum,1,0,"Pomeroy, D. and P. Mwima (2002). The State of ...",Aves,Gruiformes,Gruidae,Balearica,regulorum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Acrocephalus_sechellensis,1,0,"Rands, M. (1989). ""Saving the Seychelles brush...",Aves,Passeriformes,Acrocephalidae,Acrocephalus,sechellensis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Copsychus_sechellarum,1,0,"Komdeur, J. (1996). ""Breeding of the Seychelle...",Aves,Passeriformes,Muscicapidae,Copsychus,sechellarum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Copsychus_sechellarum,0,0,"Komdeur, J. (1996). ""Breeding of the Seychelle...",Aves,Passeriformes,Muscicapidae,Copsychus,sechellarum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Falco_punctatus,0,0,"Groombridge, J. J., Bruford, M.W., Jones, C.G,...",Aves,Falconiformes,Falconidae,Falco,punctatus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Greatest Increase

In [2]:
df_1960 = pd.DataFrame(data,
                columns =['Common_name', 1960])

grouped_df_1960 = df_1960.groupby('Common_name')[1960].sum().reset_index()
grouped_df_1960

df_2014 = pd.DataFrame(data,
                columns =['Common_name', 2014])

grouped_df_2014 = df_2014.groupby('Common_name')[2014].sum().reset_index()
grouped_df_2014

subtracted_values = (((grouped_df_2014[2014] - grouped_df_1960[1960]) / grouped_df_1960[1960]) * 100)
subtracted_values = subtracted_values.replace([np.inf, -np.inf], np.nan)

result_df = pd.DataFrame({'Common Name': grouped_df_1960['Common_name'], 'Percent of average relative change in size of populations': subtracted_values})
result_df = result_df.dropna()
biggest_inc = result_df.sort_values(by='Percent of average relative change in size of populations', ascending=False)
biggest_inc = biggest_inc.head(20)
biggest_inc

,Common Name,Percent of average relative change in size of populations
95,American plaice,9.769309e+07
3552,Silver hake / Whiting,4.221595e+07
84,American eel,4.052700e+06
1284,Dunlin,3.099530e+06
875,Capelin,1.284841e+06
968,Chub mackerel,1.013879e+06
213,Atlantic halibut,6.612345e+05
1450,European sprat,4.651218e+05
217,Atlantic mackerel,2.840074e+05
1406,Eurasian oystercatcher,5.431280e+04
3917,Stoat / Short-tailed weasel / Ermine,4.690000e+04
525,Black-tailed godwit,3.920518e+04
2527,Moose,3.677444e+04
1427,European eel,3.634867e+04
3449,Sea lamprey,3.558228e+04
950,Chimpanzee,2.932857e+04
1904,Haddock,2.478519e+04
2332,Long-tailed tit,1.665556e+04
3319,Ruddy turnstone,1.604053e+04
1081,Common pheasant,1.578819e+04

In [3]:
inc_chart = alt.Chart(biggest_inc).mark_bar().encode(
    y=alt.Y('Common Name', sort='-x'),
    x=alt.X('Percent of average relative change in size of populations:Q', scale=alt.Scale(type='log')),
    color = alt.Color('Percent of average relative change in size of populations').scale(scheme='greenblue'),
    tooltip = ['Common Name', 'Percent of average relative change in size of populations']
).properties(
    title='Top 20 Animals in the World with Greatest Increase in Population',
    width=400,
    height=500
)
inc_chart

alt.Chart(...)

## Greatest Decrease

In [4]:
df2_1960 = pd.DataFrame(data,
                columns =['Order', 1960])

grouped_df2_1960 = df2_1960.groupby('Order')[1960].sum().reset_index()
grouped_df2_1960

df2_2014 = pd.DataFrame(data,
                columns =['Order', 2014])

grouped_df2_2014 = df2_2014.groupby('Order')[2014].sum().reset_index()
grouped_df2_2014

subtracted_values2 = (((grouped_df2_2014[2014] - grouped_df2_1960[1960]) / grouped_df2_1960[1960]) * 100)
subtracted_values2 = subtracted_values2.replace([np.inf, -np.inf], np.nan)

result_df2 = pd.DataFrame({'Order': grouped_df2_1960['Order'], 'Percent of average relative change in size of populations': subtracted_values2})
result_df2 = result_df2.dropna()

biggest_dec = result_df2.sort_values(by='Percent of average relative change in size of populations', ascending=True)
biggest_dec = biggest_dec.head(17)
biggest_dec

,Order,Percent of average relative change in size of populations
15,Aulopiformes,-100.000000
100,Procellariformes,-100.000000
103,Pterocliformes,-100.000000
105,Rhinopristiformes,-100.000000
65,Istiophoriformes,-100.000000
3,Acropomatiformes,-99.975561
88,Perissodactyla,-99.975286
51,Esociformes,-99.517273
27,Centrarchiformes,-99.353300
10,Anseriformes,-97.900274
24,Carnivora,-97.106247
60,Gruiformes,-94.968772
127,Trachichthyiformes,-88.559322
107,Rodentia,-77.024248
86,Perciformes,-58.912162
124,Testudines,-47.843432
119,Strigiformes,-47.758448

In [7]:
dec_chart = alt.Chart(biggest_dec).mark_bar().encode(
    y=alt.Y('Order', sort = 'x'),
    x=alt.X('Percent of average relative change in size of populations:Q', scale=alt.Scale(domain=[0, -100])),
    color = alt.Color('Percent of average relative change in size of populations').scale(scheme='purpleblue', reverse=True),
    tooltip = ['Order', 'Percent of average relative change in size of populations']
).properties(
    title='Top 20 Orders in the World with Greatest Decrease in Population',
    width=400,
    height=500
)
dec_chart

alt.Chart(...)

In [8]:
inc_chart.save('inc_chart.html')

In [9]:
dec_chart.save('dec_chart.html')